### ISSUE TITLE
Prompt handling in BatMud

### ISSUE THREAD

**Issue by x1a0** [Blightmud/Blightmud#252]
**Describe the bug**
Prompt is not placed in the input line:

**To Reproduce**
If you connect to `bat.org 2023` and choose `2` to visit the game, you should be able to see.

**What terminal are you using?**
Windows Terminal (WSL)

**What mud were you playing?**
`bat.org 2023`

**Screenshots**
![image](https://user-images.githubusercontent.com/205756/103468216-0cf7ec00-4d57-11eb-87a6-dc59f480da4c.png)

**Comment by LiquidityC** [comment]
Are you expecting the prompt line from the mud to be visible in the input area like is common in tinyfugue?

**Comment by x1a0** [comment]
Hmm that's my understanding of prompt (like shell prompt).
I mean if connecting with `telnet`, ofc there is no input area. But the input would be in the prompt line?

**Comment by Xandaros** [comment]
For the most part, a prompt is just a line without a newline character. If you use something like telnet, that will cause you to input right after the prompt line.
Blightmud moves the input buffer to a dedicated area.
Whether you move the prompt into the input area to keep it in front of the input, or whether you keep it in the output area because it is technically output, is a philosophical question.

Blightmud keeps it in the output, which I personally prefer.
There is currently no way of moving it into the input line, but you can put it in the status area with a script if you want.

**Comment by x1a0** [comment]
@Xandaros Thanks for the explanation and the hint. It's not a bug then. I will try to solve it with Lua 👍

**Comment by LiquidityC** [comment]
Just as some interesting history on this. Tinyfugue which I started out with 10 years ago handles prompt like this and that's how I played. Later I learned that most other TF users actually scripted it out. The reason being that prompts would vary in size on some muds or be really long and leave little room for input. On some muds the prompt is more then one line which also didn't look great. 

When I started building Blightmud I used this method that you expected but after some playing and looking at other clients I got annoyed with it and reverted to the handling we have today.

Theoretically we could add a config to allow "in input line prompt". But I doubt it would see any major usage.

As @Xandaros mentioned. You can easily script it into the status area/line and get a much nicer experience with it that way.
