### ISSUE TITLE
Blank lines in log files.

### ISSUE THREAD

**Issue by lisdude** [Blightmud/Blightmud#283]
This seems like the same issue from issue #167, just in a different place. The log file is filled with blank lines where the regular output isn't.

**Reproduce**
1. Enable logging.
2. Connect to lisdude.com:1180
3. Type: longline2

The log file will then have blank spaces that shouldn't be there.

**Comment by LiquidityC** [comment]
The blank lines turned out to be the prompt being logged. Code is in effect that will prevent blank prompts from being logged. 

There is still a chance for log artifacts due to how data is received. This is a bigger hurdle to fix because I want the logging to be instant and fixing this will require a short delay in logging. I'll have to tackle that in the future if it becomes a big issue.

**Comment by LiquidityC** [comment]
Closing this one for now.
