### ISSUE TITLE
Duplicate lines in output.

### ISSUE THREAD

**Issue by lisdude** [Blightmud/Blightmud#368]
**Describe the bug**
When certain output is received, the line is duplicated halfway through.
<img width="1707" alt="Screen Shot 2021-08-04 at 2 14 30 PM" src="https://user-images.githubusercontent.com/4994688/128241231-4ea96a8b-7ea7-4879-8cea-9780aac84dba.png">

You can see in the screenshot that the line begins with `=> {"<help>", "<text>"` and appears twice. It should look like this:
<img width="1704" alt="Screen Shot 2021-08-04 at 2 15 42 PM" src="https://user-images.githubusercontent.com/4994688/128241392-95dc1e69-6922-4443-8a8b-4231c3a510d2.png">

If you scroll up and then back down, it sometimes fixes the problem. Other times it only reduces the amount of cutoff text displayed.

(This happens on less ugly examples, but this is the only one I could reliably reproduce.)

**To Reproduce**
1. Connect to `lisdude.com:1180`
2. Type: `textblock`

**What terminal are you using?**
iTerm2

**What mud were you playing?**
This occurs randomly on MOOs I connect to, but I have a test server running with a particular reproducible instance above.

**Comment by LiquidityC** [comment]
Thanks. I'm guessing this has something to do with content arriving in separate packets. I'm semi off on vacation but I'll dig into it when I'm back in action in 2 weeks

**Comment by LiquidityC** [comment]
Ok, since I'm the type of guy who has problems leaving things for later I took a look at this.

The problem was "separate packages". Eg. All that content being divided into two packages. Printing the first and the the second. The thing it we have logic in place for this. This became a combination of 2 things.

- 1. The MOO sending large content without newlines leaving this to be "wrapped" by the client.
- 2. Out "is this unterminated content a prompt" logic printing what had been received so far as a prompt.

If you look at the first print screen it's clear that the "first" print has crappy line wrapping. The second has nice line wrapping which takes spaces and words into account.

The fix here is essentially. If the content in the receive buffer is larger then 500 chars it's probably not a prompt. So leave it in the buffer. This solution isn't fail safe. But I think it will deal with the bulk of the problem. I'll let it run and see if any problems bubble up from the change. For reference, the receive buffer in this example was >3000 bytes. 

I know MOOs don't have prompts. But other muds do and I want blightmud to feel idempotent and not need to be told what mud type you're playing.

I'll be merging shortly.
