### ISSUE TITLE
Leaking triggers and gags.

### ISSUE THREAD

**Issue by robg204** [Blightmud/Blightmud#603]
Hello,

Since coming back to Blightmud, I've had a recurring problem where lines that would match triggers with gag=true are only partly consumed, or parts are repeated out for reasons that I don't quite understand. These problems were non-existent in the pre 1.0/1.0 line, but at some point seems to have been introduced.  I'm not sure how to go about troubleshooting or gathering details for this type of problem.  For example, I have a "^Your Holy Shield" {gag=true} trigger, and in the attached screenshot you can see it coming through in its entirety once, and in part twice more.  It still MOSTLY works, as there would otherwise be 12 of them in this space, but still...
![image](https://user-images.githubusercontent.com/49252009/171972031-78aa162c-e592-452e-a18e-b9828d23c19a.png)

I also know that I'm not alone in this, another contributor here has the same problems.  We both play the same two muds with a common core: 3-kingdoms and 3-scapes.  I'm not sure if this is a packet assembly issue or what, but would love to understand how to solve this problem, and would happily take suggestions on how to collect better data with which to report it.

Oh, I should mention, in these broken fragmented cases, it generally is not causing the trigger to match, which lead me to assume theres some kind of packet parsing problem.  This problem is unique for me to Blightmud on these games.

**Comment by LiquidityC** [comment]
Oh. That's no good.

Could you please include the code for the trigger you are expecting to match.
A copy of the full line you are expecting to trigger on and a log where the problem occurs where you have verbose logging on `Blightmud -V`?

**Comment by robg204** [comment]
Sure, I'll gather what I can, but to be clear, this is _rampant_, while the sample screen shot above is rather tame, it manifests in many ways, halves of lines repeating mid screen, you name it.  Similar issues with tt++ are actually why I sought out Blightmud in the first place.  Since returning, I've been living with it, but some triggers causing a line to just be displayed 5x in a row, etc has really caused problems.  I'm not sure what trigger specifically I should include, because it's basically all of my triggers.

Here are just some of them:
```
[**]   28 : ^A cask of chaotic energy +enabled -gag -raw -prompt count: 1
[**]   29 : ^You cannot go       +enabled -gag -raw -prompt count: nil
[**]   30 : ^(ST|A):.*           +enabled +gag -raw -prompt count: nil
[**]   31 : ^HP:.*               +enabled +gag -raw -prompt count: nil
[**]   32 : ^\w+ tells you:      +enabled -gag -raw -prompt count: nil
[**]   26 : ^\x1b\[45m(.*)\((.*)\) +enabled +gag +raw -prompt count: nil
[**]   27 : ^\w+ dealt the killing blow +enabled -gag -raw -prompt count: nil
and in another triggergroup
!!! 1: ^$
!!! 2: ^The mutant radiates, irritating your skin.$
!!! 3: ^The mutant bites you, leaving a festering wound!
!!! 4: shakes off the darts from the taser!$
!!! 5: resistances crumble under a Hex of Shattering!$
!!! 6: ^Your shot tears through
!!! 7: ^Your weakness identification system directs your attack to a weak spot!
!!! 8: ^\*+THA?WH?ACK\*
!!! 9: ^The mutant splashes you with radioactive goo!
!!! 10: ^The mutant screams, bellowing radioactive waves of energy at you!
!!! 11: ^You drive your attack past
!!! 12: ^Automating: gouge
!!! 13: ^They are already blinded!
!!! 14: ^Your thumbs are too tired to gouge right now
!!! 15: ^\w+'s mending powers
!!! 16: ^The mutant touches you, instantly causing your flesh to boil!
!!! 17: ^Your shield blocks
```

The -V log shows the same weirdness, with half lines and whatnot.  This seems to get worse if theres any latency on the network, and this example is from about 6 seconds of play with a couple examples.  Of course, immediately after stopping the log, a bunch more obvious examples took place. :)  Typically I gag a lot of things from the main output window and put the output into different files for tmux windowing, or into my status bar for combat related things.

![image](https://user-images.githubusercontent.com/49252009/172010521-d7f6a0d2-4f03-42c3-9be5-73bf741006d2.png)

[20220604.095900.log](https://github.com/Blightmud/Blightmud/files/8838096/20220604.09.59.00.log)

**Comment by LiquidityC** [comment]
Ok. I know what this is. Sadly it's a really annoying caveat with muds that don't send `IAC:GA` or `IAC:EOR`. Currently if a line is split between two network packages. Eg:
`Your shield blocks` blightmud will assume that line is a prompt. Once the next package arrives containing the rest of the line ` a disgusting goblins attack.` blightmud will assemble the full line and make it print nicely.

Your scripts are however highlighting this flaw by not matching the first receive because it's a prompt line and then gagging the line that is intended to "fix the visual artifact". I'm guessing your mud doesn't even use a prompt line does it? It's just a blank line? That's why you didn't have this issue before.

The packet thing will be the reason you're seeing this issue more during high latency.

Now. I've tackled this issue before and never managed a rock solid solution. Neither has TT++ and neither has Mudlet (Mudlet doesn't like non GA muds). Tinyfugue did it well by separating the prompt from the output. That is in fact why we have a separation between prompts and output lines in Blightmud because I originally did what TF did as a default.

This is what I'm planning. If it works it will be the next major release of Blightmud.

- The last line of the output area above the status bar will be dedicated to drawing the mud provided prompt. On some muds this is just a blank line. On others it has content.
- Prompts will no longer flow into the output window of the mud. They will be in the log but not in the output. If you don't like this you can remedy it with a prompt trigger.
- This should prevent future confusions regarding what is a prompt and what is a regular line.
- It will gracefully handle partially received content by sometimes rendering output in the prompt line but should quickly recover once new data arrives.

**Comment by robg204** [comment]
The two muds do send prompts, prompt do not necessarily send newlines, although anyone who scripts on the muds pretty much instantly sets their prompt to >$nl$, which is how my script for instance can tell when the text for a room is complete, the prompt is only sent when action has been taken by the user.  If you're just idle and tells for instance are coming in over time, things just end in new lines (although again, they don't NEED to, but typically the userbase complains about anything that doesn't end in NL.

**Comment by LiquidityC** [comment]
Makes sense. I guess that "complaining" is dues to the mud not sending GA making it hard to determine what's a prompt and what's not.

The PR I just submitted here: #604
Think you could check that branch out and see how it runs for you? Based on my tests it's a lot more solid. At least for the split_screen players.

A change to my previous comments. Non GA muds will still get the muds prompt printed in the output area when playing. Players who play GA muds will have to configure their preferred setup through a prompt trigger. Hence this is a major version bump.

**Comment by robg204** [comment]
Oh I should note, the prompt for us is basically throw away.  It's possible to add all kinds of stuff like HP, mana, all that to, but pretty much 99.9997% of people just set it to ```>$nl``` :) I'll try out the branch and let you know ASAP!

**Comment by robg204** [comment]
New branch basically completely solves the problem. I haven't seen what I've dubbed a "leak" since switching.  Will continue to run but it went from several "leaks" per round (2 seconds) to zero in 5+ minutes.  This has restored my sanity.  Thank you.

**Comment by LiquidityC** [comment]
No worries. Based on my tests it performed quite well also. There is the "no prompt in the output" change for muds that use GA which might not go down great with everyone. We'll see. I'll merge that PR and write some release notes for the future. I'll let it ride for a week or so before making an official 3.7 release.

**Comment by Xandaros** [comment]
> 1)  Insofar as the availability of local buffer space permits,
         data should be accumulated in the host where it is generated
         until a complete line of data is ready for transmission, or
         until some locally-defined explicit signal to transmit occurs.
         This signal could be generated either by a process or by a
         human user.
         [...]
> 2)  When a process has completed sending data to an NVT printer
         and has no queued input from the NVT keyboard for further
         processing (i.e., when a process at one end of a TELNET
         connection cannot proceed without input from the other end),
         the process must transmit the TELNET Go Ahead (GA) command.

Wouldn't it be great if MUDs were actually telnet compliant? It would make things so much easier...

Sorry, I had to :D
