### ISSUE TITLE
MTTS default should include screen reader if BM started in reader mode

### ISSUE THREAD

**Issue by Xandaros** [Blightmud/Blightmud#685]
Currently, Blightmud always sends 271 as the MTTS (in the ttype module)

If Blightmud is started in reader mode, the default should include 64 to indicate that the client is using a screen reader. The final default MTTS value for reader mode should then be 335.

It might be worth extending the ttype module with APIs to (de-)select individual parts of the MTTS value and calculate the MTTS value when it is sent, rather than storing it as a number.

**Comment by LiquidityC** [comment]
We can definitely make this more modular. We'll also need to make the "mode" available to lua. 

Details about ttype here: https://tintin.mudhalla.net/protocols/mtts/

**Comment by LiquidityC** [comment]
Turns out the existing options to modify MTTS are broken and never worked. The way I'm choosing to fix them will be a breaking change. My thought is that if nobody reported a bug before now we might get away with not doing a major release despite a breaking change.

But perhaps that's just conservative thinking and we should just do a major release even though very little has been added?

**Comment by cpu** [comment]
> But perhaps that's just conservative thinking and we should just do a major release even though very little has been added?

Version numbers are free :-) I'd vote for frequent semver motivated releases even if it means not every major release is feature packed.
