### ISSUE TITLE
Setting to hide_bottombar (status_area)

### ISSUE THREAD

**Issue by daiimus** [Blightmud/Blightmud#751]
Just a simple feature request to hide the bottom bar. Ideally, this would also highlight the input column with a '>' or something similar. Thanks for reading my request!

**Comment by LiquidityC** [comment]
To fit nicely into the current lua I think we should just start allowing `blight.status_height(0)`. I'm not sure how far needed changes will propagate. This might become fiddly.

As for prefixing the prompt with `> `. This should probably be it's own feature. Eg. `prompt.set_prefix("> ")` and not be something that happens when the status area is "disabled".
